# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:residues

# Setup
title:            residues
tagline:          'residues'
description:      'eARTh, humans, animals, machines'
url:              http://residues.github.io

baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           roberta colavecchio
  url:            https://nl.linkedin.com/pub/roberta-colavecchio/bb/653/5a7

paginate:         5

# Custom vars
icon:             /assets/images/logo.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/r_colavecchio
    desc:         follow me on twitter

  - icon:         facebook
    url:          https://www.facebook.com/robertacolavecchio
    desc:         add me on facebook

  - icon:         linkedin
    url:          https://nl.linkedin.com/pub/roberta-colavecchio/bb/653/5a7
    desc:         connect to me on linkedin

  - icon:         instagram
    url:          https://instagram.com/robertacolavecchio/
    desc:         follow me on instagram
    
menu:
  - title:        home
    url:          /

  - title:       residues
    url:          /residues

  - title:        roberta
    url:          /roberta

  - title:        messmates
    url:          /massmates

  - title:        thresholds
    url:          /thresholds

  - title:        links
    url:          /links

copyright:
  author:         Camporez
  url:            http://camporez.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
